# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'projection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10projection.proto\x12\x16pythianRisk.projection\" \n\x0eTimeSeriesData\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x81\x01\n\x11ProjectionRequest\x12\x34\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32&.pythianRisk.projection.TimeSeriesData\x12\x36\n\x05model\x18\x02 \x01(\x0e\x32\'.pythianRisk.projection.ProjectionModel*l\n\x0fProjectionModel\x12\x1c\n\x18PROJECTION_MODEL_UNKNOWN\x10\x00\x12\t\n\x05\x41RIMA\x10\x01\x12\x19\n\x15\x45XPONENTIAL_SMOOTHING\x10\x02\x12\x15\n\x11LINEAR_REGRESSION\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROJECTIONMODEL']._serialized_start=210
  _globals['_PROJECTIONMODEL']._serialized_end=318
  _globals['_TIMESERIESDATA']._serialized_start=44
  _globals['_TIMESERIESDATA']._serialized_end=76
  _globals['_PROJECTIONREQUEST']._serialized_start=79
  _globals['_PROJECTIONREQUEST']._serialized_end=208
# @@protoc_insertion_point(module_scope)
